### ISSUE TITLE
How to use this image to run the https://github.com/geb/geb-example-gradle inside a docker container?

### ISSUE THREAD

**Issue by duc-gp** [geb/ci-docker-image#1]
Hello,

unfortunately I havent found any documentation on this. Can anyone provide information how to use this image? When I try to run the tests inside the docker container I get:

root@66381f11969c:~# ./gradlew chromeTest --tests GebishOrgSpec

> Task :chromeTest

GebishOrgSpec > can get to the current Book of Geb FAILED
    geb.driver.DriverCreationException: failed to create driver from callback 'script1545146894339779105240$_run_closure2$_closure3$_closure6@2576bb5b'
        at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
        at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy:85)
        at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy)
        at geb.driver.CachingDriverFactory$SimpleCache.get(CachingDriverFactory.groovy:32)
        at geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:84)
        at geb.Configuration.createDriver(Configuration.groovy:374)
        at geb.Configuration.getDriver(Configuration.groovy:363)
        at geb.Browser.getDriver(Browser.groovy:119)
        at geb.navigator.factory.BrowserBackedNavigatorFactory.<init>(BrowserBackedNavigatorFactory.groovy:35)
        at geb.Configuration.createNavigatorFactory(Configuration.groovy:427)
        at geb.Browser.createNavigatorFactory(Browser.groovy:141)
        at geb.Browser.getNavigatorFactory(Browser.groovy:129)
        at geb.Page.init(Page.groovy:144)
        at geb.Browser.createPage(Browser.groovy:908)
        at geb.Browser.to(Browser.groovy:588)
        at geb.Browser.to(Browser.groovy:577)
        at geb.spock.GebSpec.methodMissing(GebSpec.groovy:60)
        at GebishOrgSpec.can get to the current Book of Geb(GebishOrgSpec.groovy:7)

**Comment by erdi** [comment]
This image is intended for internal use - namely to run Geb test harness and Geb examples in CircleCI. This goal is achieved, see [CircleCI config for geb/geb-example-gradle](https://github.com/geb/geb-example-gradle/blob/master/.circleci/config.yml#L5), [gebish/ci image on docker hub](https://hub.docker.com/r/gebish/ci/dockerfile), [definition of gebish/ci image at verison 5](https://github.com/geb/ci-docker-image/blob/f179c1f644c2cdec6595bbd96bf9ad4fa922343f/Dockerfile) and [the latest passing build for master of geb/geb-example-gradle](https://circleci.com/gh/geb/geb-example-gradle/52).

You can use all this as an example setup but note that this is intended for Geb internal use so I won't be able to provide you with any support in setting this up for yourself.
